---

- name: install cuda computing roles
  hosts:  "{{ _host_ | default('localhost') }}"


  tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes

    - name: Install CUDA libraries and tools
      become: yes
      apt:
        pkg: 
          - system76-cuda-latest
          - system76-cudnn-11.2
          - nvidia-cuda-toolkit
        state: latest



