---

- name: install cuda computing roles
  hosts:  "{{ _host_ | default('localhost') }}"


  tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes

    - name: Install CUDA libraries and tools
      become: yes
      apt:
        pkg: 
          - system76-cuda-latest
          - system76-cudnn-11.2
          - nvidia-cuda-toolkit
          - python3-numba
          - nvtop
        state: latest


    - name: Python pacakges
      pip:
        name:
          - nvidia-cudnn-cu11
          - tensorflow[and-cuda]
          - torch
          - pyro-ppl

    - name: add envornoment variables
      block:
        - name: CUDNN path
          lineinfile:
            path: ~/.bashrc
            line: 'export CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))'
            regexp: '^export CUDNN_PATH=.*'
            state: present
            insertafter: EOF
            create: no
        - name: LD_LIBRARY_PATH #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib
          lineinfile:
            path: ~/.bashrc
            line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib'                                   
            regexp: '^export LD_LIBRARY_PATH=.*'         
            state: present
            insertafter: EOF
            create: no
        
        - name: make gobal
          become: no
          shell: |
            echo "#!/bin/bash" > /tmp/cuda.sh
            echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> /tmp/cuda.sh
            echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> /tmp/cuda.sh

        - name: make global
          become: yes
          copy:
            src: /tmp/cuda.sh
            dest: /etc/profile.d/

