---

- name: install development roles
  hosts:  "{{ _host_ | default('localhost') }}"

  tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes

    - name: Install essentials
      become: yes
      apt:
        pkg: 
          - build-essential
          - sqlite3
          - software-properties-common
          - apt-transport-https
          - vim  
          - wget
          - curl
          - code
          - git
          - git-lfs
          - gh
          - atool
          - xvfb
          - nodejs
          - npm
          - libsnappy-dev
        state: latest
        update_cache: false

    - name: install gitgib cli extensions
      shell: |
        gh extension install actions/gh-actions-cache
        
    - name: configure vscode
      shell: |
        code --install-extension rdnlsmith.linux-themes
        sed -i -e 's/"workbench.colorTheme": ".*"/"workbench.colorTheme": "Yaru"/g' "$HOME/.config/Code/User/settings.json"
        code --install-extension lisoveliy.starcoderex
        code --install-extension ms-vscode-remote.remote-containers
        code --install-extension ms-azuretools.vscode-docker
        code --install-extension ms-python.python
        code --install-extension isudox.vscode-jetbrains-keybindings

    - name: configure git
      shell: git config --global credential.helper store

    - name: Install python
      become: yes
      apt:
        pkg:
          - python3
          - python-is-python3
          - python3-pip  
          - python3-dbus
          - python3-dev
          - python3-gi
          - python3-jupyter-console
          - python3-jupyter-core
            #- python3-matplotlib
          - python3-nacl
            #- python3-numpy
            #- python3-pandas
          - python3-psycopg2
          - python3-pymacaroons
          - python3-pymysql
          - python3-pytest
            #- python3-requests
            #- python3-sklearn
          - python3-tk
          - python3-venv
          - python3-virtualenv
          - python3-jupyterlab-server
          - python3-lxml
          - python3-pyquery
          - python3-snappy
          - python3-graphviz
          - pipx
        state: latest
        update_cache: false

    - name: Install and upgrade pip pacakges
      become: no
      pip: 
        name:
          - include-pycharm-modules
          - pandas
          - numpy
          - requests
          - ptpython
          - seaborn
          - jupyterlab
          - sqlalchemy
          - tables
          - pyarrow
          - scikit-learn
          - scikit-optimize
          - h5py
          - click
          - pygwalker
          - python-sql
          - dill
          - tensorflow
          - tensorflow-probability
          - torch 
          - lets-plot

    - name: pyenv and poetry
      become: no
      shell: |
        curl -fsSL https://pyenv.run | bash
        curl -sSL https://install.python-poetry.org | python3 -
      
    - name: add deadsnakes repository
      become: yes
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install python 3.8, 3.9
      become: yes
      apt:
        pkg:
          - python3.8
          - python3.8-venv
          - python3.8-distutils
          - python3.9
          - python3.9-venv
          - python3.9-distutils

    - name: add vscode repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache: no

    - name: add dbeaver repository
      become: yes
      ansible.builtin.apt_repository:           
        repo: ppa:serge-rider/dbeaver-ce
        state: present
        update_cache: no

    - name: add jetbrains repository
      become: yes
      block:
        - name: get key
          ansible.builtin.get_url:           
            url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
            dest: /etc/apt/trusted.gpg.d/jetbrains-unofficial.asc

        - name: add repo
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/trusted.gpg.d/jetbrains-unofficial.asc] http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main"
            state: present
            update_cache: no

    - name: add repo
      become: yes
      apt:
        update_cache: yes

    - name: Install IDEs
      become: yes
      apt:
        pkg:
          - code
          - pycharm-community
          - pycharm-professional
          - intellij-idea-community
          - intellij-idea-ultimate
          - datagrip
          - rider
          - geany
          - dbeaver-ce
          - libsnappy-jni
        state: latest
        update_cache: no
       
    - name: install Cpython extensions for pycharm professional
      shell: /usr/bin/python3 /opt/pycharm-professional/plugins/python/helpers/pydev/setup_cython.py build_ext --inplace
      become: yes
          
    - name: install Cpython extensions for pycharm community
      shell: /usr/bin/python3 /opt/pycharm-community/plugins/python-ce/helpers/pydev/setup_cython.py build_ext --inplace
      become: yes
        
    - name: Jupyter lab service
      become: yes
      copy:
        dest: /etc/systemd/system/jupytherlab.service
        content: |
          [Unit]
          Description=jupytherlab
          [Service]
          Type=simple
          ExecStart=/home/kic/.local/bin/jupyter-lab --ip=0.0.0.0 --port 17256 --NotebookApp.max_buffer_size=12000000000 --LabApp.token='{{ _token_ }}'
          WorkingDirectory=/home/kic/
          User=kic
          Group=kic
          Restart=on-failure
          RestartSec=5s
          [Install]
          WantedBy=multi-user.target

    - name: Jupyter lab service
      become: yes
      systemd:
        name: jupytherlab
        state: started
        enabled: yes

    - name: Environment
      become: yes
      copy:
        dest: /etc/profile.d/develop_env.sh
        content: |
          export PYTEST_ADDOPTS="-s"
          export PYTORCH_ALLOC_CONF="max_split_size_mb:64,garbage_collection_threshold:0.6"

          
