---

- name: install development roles
  hosts:  "{{ _host_ | default('localhost') }}"

  tasks:

    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes

    - name: Install essentials
      become: yes
      apt:
        pkg: 
          - build-essential
          - sqlite3
          - software-properties-common
          - apt-transport-https
          - vim  
          - wget
          - curl
          - code
          - git
          - atool
          - xvfb
          - nodejs
          - npm
        state: latest
        update_cache: false

    - name: Install python
      become: yes
      apt:
        pkg:
          - python3
          - python-is-python3
          - python3-pip  
          - python3-dbus
          - python3-dev
          - python3-gi
          - python3-jupyter-console
          - python3-jupyter-core
          - python3-matplotlib
          - python3-nacl
          - python3-numpy
          - python3-pandas
          - python3-psycopg2
          - python3-pymacaroons
          - python3-pymysql
          - python3-pytest
          - python3-requests
          - python3-sklearn
          - python3-tk
          - python3-venv
          - python3-virtualenv
          - python3-jupyterlab-server
        state: latest
        update_cache: false

    - name: Install and upgrade pip pacakges
      become: no
      pip: 
        name:
          - seaborn
          - jupyterlab

    - name: add deadsnakes repository
      become: yes
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present


    - name: add vscode repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: add dbeaver repository
      become: yes
      ansible.builtin.apt_repository:           
        repo: "deb https://dbeaver.io/debs/dbeaver-ce /"
        state: present

    - name: add jetbrains repository
      become: yes
      block:
        - name: get key
          ansible.builtin.get_url:           
            url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
            dest: /etc/apt/trusted.gpg.d/jetbrains-unofficial.asc

        - name: add repo
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/trusted.gpg.d/jetbrains-unofficial.asc] http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main"
            state: present

    - name: Install IDEs
      become: yes
      apt:
        pkg:
          - code
          - pycharm-community
          - pycharm-professional
          - intellij-idea-community
          - intellij-idea-ultimate
          - datagrip
          - rider
          - geany
          - dbeaver-ce
        state: latest
        update_cache: false
        
    - name: Jupyter lab service
      become: yes
      copy:
        dest: /etc/systemd/system/jupytherlab.service
        content: |
          [Unit]
          Description=jupytherlab
          [Service]
          Type=simple
          ExecStart=/home/kic/.local/bin/jupyter-lab --ip=0.0.0.0 --port 17256 --LabApp.token=''
          WorkingDirectory=/home/kic/
          User=kic
          Group=kic
          Restart=on-failure
          RestartSec=5s
          [Install]
          WantedBy=multi-user.target

    - name: Jupyter lab service
      become: yes
      systemd:
        name: jupytherlab
        state: started
        enabled: yes

