---

- name: install gnome roles
  hosts:  "{{ _host_ | default('localhost') }}"

  tasks:        
    - name: Install gnome software
      become: yes
      apt:
        pkg:
          - shutter
          - dconf-editor
          - gnome-tweaks
          - gedit-plugin-multi-edit
          - gnome-system-log
          - gnome-shell-extension-gsconnect
        state: latest
                  

