---
- hosts: all
  become: true

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Unbound
      apt:
        name: unbound
        state: present
        update_cache: yes

    - name: Deploy Unbound minimal configuration
      copy:
        dest: /etc/unbound/unbound.conf
        content: |
          server:
            interface: 127.0.0.1
            port: 53
            do-not-query-localhost: no
            access-control: 127.0.0.1/24 allow
            do-ip6: no
            hide-identity: yes
            hide-version: yes
            #harden-shortbuf: yes
            qname-minimisation: yes
            edns-buffer-size: 4096
            minimal-responses: yes
            prefetch: yes
          forward-zone:
            name: "."
            forward-addr: 1.1.1.1
            forward-addr: 8.8.8.8
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart unbound

    - name: Ensure Unbound is enabled and running
      systemd:
        name: unbound
        state: started
        enabled: true

    - name: Stop and disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove systemd-resolved symlink for resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create /etc/resolv.conf with local nameserver
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 127.0.0.1
        owner: root
        group: root
        mode: '0644'

    - name: Stop and disable libvirtd service
      systemd:
        name: libvirtd
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Stop default libvirt network if active
      command: virsh net-destroy default
      ignore_errors: yes
      changed_when: false

    - name: Disable autostart for default libvirt network
      command: virsh net-autostart --disable default
      ignore_errors: yes
      changed_when: false

    - name: Configure Docker daemon.json
      copy:
        content: |
          {
            "dns": ["8.8.8.8", "127.0.0.1"]
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: restart docker

    # TODO make sure in /etc/NetworkManager/NetworkManager.conf under [main] is >dns=none<

    - name: Deploy NetworkManager dispatcher script to enforce Unbound DNS
      copy:
        dest: /etc/NetworkManager/dispatcher.d/99-unbound-dns
        content: |
          #!/bin/bash
          IFACE=$1
          STATUS=$2

          if [ "$STATUS" = "up" ]; then
            echo "Network $IFACE is up - setting DNS to 127.0.0.1 for Unbound"
            echo "nameserver 127.0.0.1" > /etc/resolv.conf
            systemctl restart unbound
            if systemctl is-active --quiet systemd-resolved; then
              systemctl stop systemd-resolved
            fi
            echo "DNS set to Unbound at 127.0.0.1"
          fi
        owner: root
        group: root
        mode: '0755'

  handlers:
    - name: Restart unbound
      systemd:
        name: unbound
        state: restarted

