---
- name: Install Basis System
  hosts: localhost
  become: yes
  vars:
    user_id: "{{ ansible_facts.env.SUDO_USER }}"
    # also had "quiet" and "resume=UUID=5067b521-24b9-4173-92b1-5fef7bb6b8ff" 
    grub_params: "mitigations=off loglevel=3 intel_pstate=active amd_iommu=off i915.enable_rc6=1 i915.enable_psr=1 i915.enable_fbc=1"
    directories:
      - /opt/uv/tools
      - /opt/uv/python
      - /opt/uv/cache
      - /opt/appimages
      - /opt/manual-binaries
      - /home/.shared/downloads
      - /home/.shared/data
      - /home/.shared/data/work
      - /home/.shared/data/mine
      - /home/.shared/data/public
      - /home/.shared/data/public/yfinance
      - /home/.shared/sources
      - /home/.shared/sources/work
      - /home/.shared/sources/mine
      - /home/.shared/sources/mine/notebooks
      - /home/.shared/sources/public
      - /home/.shared/documents
      - /home/.shared/documents/work
      - /home/.shared/documents/mine
      - /home/.shared/documents/public
      - /home/.shared/audios
      - /home/.shared/audios/mine
      - /home/.shared/audios/public
      - /home/.shared/audios/public/music
      - /home/.shared/images
      - /home/.shared/images/mine
      - /home/.shared/images/public
      - /home/.shared/videos
      - /home/.shared/videos/mine
      - /home/.shared/videos/public
  tasks:
    - name: Ensure needed tools are installed
      ansible.builtin.package:
        name:
          - util-linux
          - uv
        state: present

    - name: Get total RAM in bytes
      ansible.builtin.shell: lsmem -b --summary=only | sed -ne '/online/s/.* //p'
      register: ram_output

    - name: Set GRUB parameters including AMD GPU GTT size
      ansible.builtin.set_fact:
        grub_params: "{{ grub_params }} amdgpu.gttsize={{ ram_output.stdout }} ttm.pages_limit={{ ram_output.stdout }}"

    - name: Get current GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.command: grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub
      register: current_grub
      changed_when: false

    - name: Extract current parameters
      ansible.builtin.set_fact:
        current_params: "{{ current_grub.stdout | regex_replace('^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*)\"$', '\\1') }}"

    - name: Extract resume parameter
      ansible.builtin.set_fact:
        resume_param: "{{ current_params | regex_findall('resume=UUID=[^ ]+') | first | default('') }}"

    - name: Append resume parameter to GRUB params
      ansible.builtin.set_fact:
        grub_params: "{{ resume_param }} {{ grub_params }}"
      when: resume_param != ''

    - name: Set GRUB default kernel parameters
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_params }}"'
      notify: update-grub

    - name: Create disable-turbo-battery service
      ansible.builtin.copy:
        dest: /etc/systemd/system/disable-turbo-battery.service
        content: |
          [Unit]
          Description=Disable Intel Turbo on Battery
          After=multi-user.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/bash -c 'if [ -f /sys/module/intel_pstate/parameters/no_turbo ] && ! on_ac_power; then echo 1 > /sys/module/intel_pstate/parameters/no_turbo; fi'
          ExecStop=/bin/bash -c 'if [ -f /sys/module/intel_pstate/parameters/no_turbo ] && on_ac_power; then echo 0 > /sys/module/intel_pstate/parameters/no_turbo; fi'

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start disable-turbo-battery service
      ansible.builtin.systemd:
        name: disable-turbo-battery
        enabled: yes
        state: started
    
    - name: Install privoxy
      ansible.builtin.package:
        name:
          - util-linux
        state: present
        
    - name: Post privoxy - Ensure no_proxy includes localhost is set permanently system-wide
      become: yes
      copy:
        dest: /etc/profile.d/no_proxy.sh
        content: |
          # Set no_proxy environment variable to bypass proxy for localhost
          export no_proxy=localhost,127.0.0.1
          export NO_PROXY=localhost,127.0.0.1
        owner: root
        group: root
        mode: '0644'
        
    - name: Increase filesystem watcher limit
      become: yes
      lineinfile:
        path: /etc/sysctl.d/99-inotify.conf  # Higher precedence directory
        line: 'fs.inotify.max_user_watches=524288'
        create: yes
        owner: root
        group: root
        mode: '0644'
      notify: apply sysctl

    - name: Remove unused software
      ansible.builtin.package:
        name: 
          - bridge-utils
          - aribb24
          - depot-tools-git
          - find-the-command-git
          - gperf
          - paru  # we use yay because paru has poor ansible automation properties!
        state: absent

    - name: Install standard software
      ansible.builtin.package:
        name:
          - yay  # we use yay because paru has poor ansible automation properties!
          - foot  # fast leightweigt wayland console
          - nvim  # colored vim
          - vim  # plin vim
          - flatpak  # enble flatpak packages
          - convmv  # convert between file encodings 
          - firejail  # run any executable in a sandbox environment
          - rdfind  # find duplicate files
          - powertop  # show power consuption per process
          - progress  # show IO and estimate time
          - btop  # nice top alternative
          - meld  # file comparison
          - duplicity  # Backup tool
          - deja-dup  # GUI Frontend for duplicity
          - cups-pdf  # print to PDF
          - fzf  # fuzzy file finder
          - fuse-zip  # mount zip files
          - bonnie++  # Hard dirve benchmark tool
          - sshfs  # mount folders over ssh
          - transmission-qt  # torrent client
          - ttf-ms-fonts  # microsoft fonts
          - gparted  # disk partitioning
          - gzip  # zipper
          - unarchiver  # extract rar archives
          - torbrowser-launcher  # TOR browser
          - popsicle  # USB Boot maker
          - ventoy  # make USB stick bootable for multiple images
          - imagemagick  # Imag CLI tools
          - nmap  # network tool
          - htop  # better top
          - iftop  # top for networking
          - nvtop  # top for nvidia
          - lrzip  # lrge file compression
          - zip  # zip compressor
          - atool  # archive tools
          - ecryptfs-utils  # mount singe encrypted folder
          - hardinfo  # show hardware like in windows
          - mpv  # video player
          - ffmpeg  # video codecs and cli tools
          - syncthing  # sync files across devices
        state: present

    - name: Make aur_builder user art of group users
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        groups: 
          - wheel
          - users
        shell: /bin/bash
        state: present
      become: yes

    - name: Configure sudoers - passwordless pacman for aur_builder
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder
        create: yes
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman *"
        validate: "visudo -cf %s"
        
    - name: Setup yay config (non-interactive)
      become: yes
      become_user: aur_builder
      ansible.builtin.copy:
        content: |
          {
            "answerdiff": "None",
            "answeredit": "None", 
            "answerclean": "None",
            "mflags": "--noconfirm --needed",
            "sortby": "name"
          }
        dest: "/home/aur_builder/.config/yay/config.json"
        mode: '0644'
      register: yay_config

    - name: Make user user is part of group users
      ansible.builtin.user:
        name: "{{ user_id }}"
        groups: users
        append: true

    - name: create user data in shared location
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # owner: users
        group: users
        mode: "02770"
        recurse: true
      become: yes
      loop: "{{ directories }}"

    - name: set acl defaults
      ansible.builtin.shell: |
        setfacl -R -m g:users:rwX,u::rwx {{ item }}
        setfacl -R -d -m g:users:rwX,u::rwx {{ item }}
      become: yes
      loop:
        - /opt
        - /home/.shared
    
    - name: Install UV tools
      ansible.builtin.shell: >-
        UV_CACHE_DIR=/opt/uv/cache
        UV_TOOL_BIN_DIR=/usr/local/bin
        UV_TOOL_DIR=/opt/uv/tools
        uv tool install {{ item }} --force
      become: yes
      loop:
        - yt-dlp
        # TODO install all uv tools to the shared location

    - name: Set Environment Varaibles
      become: yes
      copy:
        dest: /etc/profile.d/basis_env.sh
        content: |
          export UV_TOOL_BIN_DIR=/usr/local/bin
          export UV_TOOL_DIR=/opt/uv/tools
          export UV_PYTHON_INSTALL_DIR=/opt/uv/python
          export UV_CACHE_DIR=/opt/uv/cache

  handlers:
    - name: update-grub
      ansible.builtin.command: update-grub
   
    - name: sysctl
      command: sysctl --system

