
---
- name: Install Development Tools
  hosts: localhost
  become: yes
  vars:
    user_id: "{{ ansible_facts.env.SUDO_USER }}"
    # The AUR helper to be used. 'yay' is a popular choice or paru
    aur_helper: "paru"
  tasks:
    - name: Install developer software
      ansible.builtin.package:
        name:
          - git
          - git-lfs  # git large files
          - github-cli  # github cli tool
          - sqlite3
          - visual-studio-code-bin
          - docker
          - docker-compose
          - uv  # Python manager
          - nvm  # nodejs manager
          - nodejs
          - gemini-cli
        state: present

    - name: config git settings and install github cli extensions
      ansible.builtin.shell: |
        git config --global credential.helper store
        # gh extension install actions/gh-actions-cache  # FIXME 

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install LazyDocker via official script
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
      async: 300
      poll: 10
      become: no

    - name: Move to general awailable place
      ansible.builtin.shell: |
        mv /home/{{ user_id }}/.local/bin/lazydocker /usr/local/bin/
      become: yes
    
    - name: Make LazyDocker executable
      file:
        path: /usr/local/bin/lazydocker
        mode: '0755'
      become: yes

    - name: Add user to docker group
      user:
        name: "{{ user_id }}"
        groups: docker
        append: yes
      become: yes  

    - name: install cursor
      become: yes
      become_user: aur_builder
      kewlfft.aur.aur:
        name: cursor-bin
        state: present
        use: "{{ aur_helper }}"
        extra_args:
          - --noconfirm
          - --skip-review
        aur_only: yes

    - name: install snapd
      become: yes
      become_user: aur_builder
      kewlfft.aur.aur:
        name: snapd
        state: present
        use: "{{ aur_helper }}"
        extra_args:
          - --noconfirm
          - --skip-review
        aur_only: yes

    - name: enable snapd
      systemd:
        name: snapd.socket
        state: started
        enabled: yes

    - name: symlink for classic snaps
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      become: yes

  # TODO install adb android tools 
  # TODO install snaps
