---
- name: Install Basis System
  hosts: localhost
  become: yes
  vars:
    user_id: "{{ ansible_facts.env.SUDO_USER }}"
    kernel_name: "Notebooks"
    notebooks_path: /home/.shared/sources/mine/notebooks
    port: 17256
    packages:
      - jupyterlab
      - ipykernel
      - pandas
      - matplotlib

  tasks:
    - name: Assert token passed
      assert:
        that: 
          - _token_ is defined
        fail_msg: "you need to define a tken via ansible-playbook jupyter.yaml -K --extra-vars '_token_=geheim'"
        success_msg: "Token defined!"

    - name: cretate env
      file: 
        path: "{{ notebooks_path }}"
        state: directory
        group: "users"
        mode: "02770"

    - name: Ensure uv installed
      ansible.builtin.package:
        name:
          - uv
        state: present

    - name: get uv location
      ansible.builtin.shell: which uv
      register: uv_path
      changed_when: false 

    - name: Create environment
      ansible.builtin.shell: UV_NO_DEFAULT=1 uv init --bare --managed-python
      become: no
      args:
        chdir: "{{ notebooks_path }}"
        creates: "{{ notebooks_path }}/pyproject.toml"
      environment:
        UV_PYTHON_INSTALL_DIR: /opt/uv/python
        UV_CACHE_DIR: /opt/uv/cache

    - name: install packages
      ansible.builtin.shell: uv add {{ item }}
      become: no
      args:
        chdir: "{{ notebooks_path }}"
      loop: "{{ packages }}"
 
    - name: sync env and install kernel
      become: no
      ansible.builtin.shell: |
        uv sync
        {{ notebooks_path }}/.venv/bin/python -m ipykernel install \
          --user \
          --name={{ kernel_name }} \
          --display-name={{ kernel_name }}
      args:
        chdir: "{{ notebooks_path }}"
 
    - name: Jupyter lab service
      become: yes
      copy:
        dest: /etc/systemd/system/jupyterlab.service
        content: |
          [Unit]
          Description=jupyterlab
          
          [Service]
          Type=simple
          ExecStart={{ uv_path.stdout }} run --directory {{ notebooks_path }} jupyter lab --port {{ port }} --NotebookApp.max_buffer_size=12000000000 --LabApp.token='{{ _token_ }}'
          WorkingDirectory={{ notebooks_path }}
          User={{ user_id }}
          Group=users
          # Restart=on-failure
          # RestartSec=5s

          [Install]
          WantedBy=multi-user.target

    - name: Jupyter lab service
      become: yes
      systemd:
        name: jupyterlab
        state: started
        enabled: yes

