---
- name: Install NVIDIA CUDA Compute-Only + Sleep Support on Garuda Sway
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    greetd_config: "/etc/greetd/config.toml"
    sway_desktop: "~/.local/share/wayland-sessions/sway-nvidia.desktop"
  tasks:
    - name: Check if kernel headers for current kernel are installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Install eventually missing kernel headers
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - linux-headers
        - linux-lts-headers
        - linux-zen-headers
        - linux-cachyos-headers
      when: item not in ansible_facts.packages

    - name: Install NVIDIA drivers for compute (DKMS)
      ansible.builtin.package:
        name:          
          - nvidia-dkms
          - nvidia-utils
          - nvidia-settings
          - nvidia-prime
          - lib32-nvidia-utils
        state: latest

    - name: Install CUDA toolkit and cuDNN
      pacman:
        name:
          - cuda
          - cudnn
        state: latest

    - name: Enable NVIDIA power management kernel options
      copy:
        dest: /etc/modprobe.d/nvidia-power.conf
        content: |
          # Required for suspend/hibernate + compute-only mode
          options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_Powerd=1 NVreg_DynamicPowerManagement=0x02
        backup: yes

    - name: Enable NVIDIA sleep services system-wide
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nvidia-suspend
        - nvidia-hibernate
        - nvidia-resume
        - nvidia-powerd

    - name: NVIDIA GPU poweroff service (sleeps until CUDA demand)
      copy:
        dest: /etc/systemd/system/nvidia-poweroff.service
        content: |
          [Unit]
          Description=Power off NVIDIA GPU after boot (iGPU rendering, CUDA wake-on-demand)
          After=multi-user.target nvidia-persistenced.service
          Wants=nvidia-persistenced.service
          
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c 'nvidia-smi -pm 0 || true'
          ExecStart=/bin/bash -c 'nvidia-smi -pl 50 || true'
          RemainAfterExit=yes
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Enable NVIDIA poweroff service
      systemd:
        name: nvidia-poweroff
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Ensure CUDA environment is sourced system-wide
      copy:
        dest: /etc/profile.d/cuda.sh
        content: |
          #!/bin/bash
          if [[ -d /opt/cuda/bin ]]; then
            export PATH=/opt/ cuda/bin${PATH:+:${PATH}}
            export LD_LIBRARY_PATH=/opt/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
            export CUDA_HOME=/opt/cuda
          fi
        mode: '0775'

    - name: Run full Garuda update
      debug:
        msg: |
          you should really run sudo garuda-update -a now to make sure initramfs is not broken!
      