---
# List timers: sudo systemctl list-timers
- name: Optimize Battery (Garuda Native)
  hosts: all
  become: yes
  vars:
    user_id: "{{ ansible_facts.env.SUDO_USER }}"
    autotune: |
      [Unit]
      Description=PowerTOP auto tune
      After=multi-user.target

      [Service]
      Type=oneshot
      ExecStart=/usr/sbin/powertop --auto-tune
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    job: |
      [Unit]
      Description=Powertop HTML report
      After=network.target
      
      [Service]
      Type=oneshot
      User=root
      ExecStart=/usr/bin/powertop --html=/home/{{ user_id }}/status/powertop.html
    timer: |
      [Unit]
      Description=Powertop report every 30 minutes
      
      [Timer]
      OnCalendar=*:0/30
      Persistent=true
      
      [Install]
      WantedBy=timers.target
  tasks:
    - name: Install Garuda-native battery tools
      package:
        name:
          - powertop
          - auto-cpufreq
          - power-profiles-daemon
        state: present

    - name: Enable auto-cpufreq (Garuda's TLP replacement)
      service:
        name: auto-cpufreq
        enabled: yes
        state: started

    - name: Run powertop auto-tune
      command: powertop --auto-tune
      ignore_errors: yes

    - name: Enable power-profiles-daemon (Garuda default)
      service:
        name: power-profiles-daemon
        enabled: yes
        state: started

    - name: Stop and disable listed services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - man-db.timer
        - ModemManager

    - name: Create status directory for powertop reports
      ansible.builtin.file:
        path: "/home/{{ user_id  }}/status"
        state: directory
        owner: "{{ user_id }}"
        group: "{{ user_id }}"
        mode: '0755'

    - name: Deploy powertop autotune and reporting
      block:
        - name: Create service and timer files
          ansible.builtin.copy:
            content: "{{ item.content }}"
            dest: "{{ item.dest }}"
            mode: '0644'
          loop:
            - { content: "{{ autotune }}", dest: "/etc/systemd/system/powertop-autotune.service" }
            - { content: "{{ job }}", dest: "/etc/systemd/system/powertop-report.service" }
            - { content: "{{ timer }}", dest: "/etc/systemd/system/powertop-report.timer" }
          become: true
        
        - name: Reload systemd and enable timer
          ansible.builtin.systemd:
            daemon_reload: true
            name: powertop-report.timer
            enabled: true
            state: started
          become: true

