---
- name: Optimize Battery (Garuda Native)
  hosts: all
  become: yes
  tasks:
    - name: Install Garuda-native battery tools
      package:
        name:
          - powertop
          - auto-cpufreq
        state: present

    - name: Enable auto-cpufreq (Garuda's TLP replacement)
      service:
        name: auto-cpufreq
        enabled: yes
        state: started

    - name: Run powertop auto-tune
      command: powertop --auto-tune
      ignore_errors: yes

    - name: Enable power-profiles-daemon (Garuda default)
      service:
        name: power-profiles-daemon
        enabled: yes
        state: started


    - name: Stop and disable listed services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - man-db.timer
        - ModemManager
        