---
# List timers: sudo systemctl list-timers
- name: Optimize Battery (Garuda Native)
  hosts: all
  become: yes
  tasks:
    - name: Install Garuda-native battery tools
      package:
        name:
          - powertop
          - auto-cpufreq
        state: present

    - name: Enable auto-cpufreq (Garuda's TLP replacement)
      service:
        name: auto-cpufreq
        enabled: yes
        state: started

    - name: Run powertop auto-tune
      command: powertop --auto-tune
      ignore_errors: yes

    - name: Enable power-profiles-daemon (Garuda default)
      service:
        name: power-profiles-daemon
        enabled: yes
        state: started


    - name: Stop and disable listed services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - man-db.timer
        - ModemManager

    - name: Create status directory for powertop reports
      ansible.builtin.file:
        path: "/home/{{ ansible_facts.user_id  }}/status"
        state: directory
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_id }}"
        mode: '0755'

    - name: Create powertop service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Powertop HTML report
          After=network.target
          
          [Service]
          Type=oneshot
          User=root
          ExecStart=/usr/bin/powertop --html=/home/{{ ansible_facts.user_id }}/status/powertop.html
        dest: /etc/systemd/system/powertop-report.service
        mode: '0644'
      become: true
      notify: reload systemd

    - name: Deploy powertop timer + enable
      block:
        - name: Create service and timer files
          ansible.builtin.copy:
            content: "{{ item.content }}"
            dest: "{{ item.dest }}"
            mode: '0644'
          loop:
            - { content: "[Unit]\nDescription=Powertop HTML report\nAfter=network.target\n\n[Service]\nType=oneshot\nUser=root\nExecStart=/usr/bin/powertop --html=/home/{{ ansible_facts.user_id }}/status/powertop.html", dest: "/etc/systemd/system/powertop-report.service" }
            - { content: "[Unit]\nDescription=Powertop report every 30 minutes\n\n[Timer]\nOnCalendar=*:0/30\nPersistent=true\n\n[Install]\nWantedBy=timers.target", dest: "/etc/systemd/system/powertop-report.timer" }
          become: true
        
        - name: Reload systemd and enable timer
          ansible.builtin.systemd:
            daemon_reload: true
            name: powertop-report.timer
            enabled: true
            state: started
          become: true

