---
- name: Install Custom Cachyos Kernel for Garuda Linux
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure base build tools and system dependencies are installed
      ansible.builtin.package:
        name:
          -           - hardinfo
          - neovim
          - python3
          - python3-pip
          - grub-pc
          - build-essential 
          - cmake
          - btrfs-progs
          - linux-headers-generic
          - ecryptfs-utils
          - vim
          
          - vlc
          - zip
          - lrzip
          - iftop
          - htop
          - nmap
          - unar
          - unison
          - usb-creator-gtk
          - imagemagick
          - ubuntu-restricted-extras
          - wget
          - xvfb
          - usb-creator-gtk
          - tor
          - torbrowser-launcher
          - gzip
          - gparted 
          - tlp           
          - google-chrome-stable
          - wmctrl
          - ttf-mscorefonts-installer
          - msttcorefonts
          - transmission
          - sshfs
          - neovim
          - bonnie++
          - gcp
          - fuse-zip
          - doublecmd-common
          - fzf
          - printer-driver-cups-pdf
          - duplicity
          - deja-dup
          - snapd
          - meld
          - btop
          - unixodbc
          - unixodbc-dev
          - progress
          - powertop
          - neofetch
          - hexchat
          
          - rdfind
          - firejail
          - convmv
        state: latest

        # TODO uv tool install yt-dlp and add home/.local/bin to path
