---
- name: Replace systemd-resolved with Unbound
  hosts: all
  become: yes
  tasks:
    - name: Install Unbound
      package:
        name: unbound
        state: present

    - name: Gather service facts
      service_facts:

    - name: Configure Unbound
      copy:
        dest: /etc/unbound/unbound.conf
        content: |
          server:
            interface: 127.0.0.1
            interface: ::1
            port: 53
            do-ip6: yes
            do-not-query-localhost: no
            access-control: 127.0.0.0/8 allow
            access-control: ::1/128 allow
            hide-identity: yes
            hide-version: yes
            edns-buffer-size: 4096
            minimal-responses: yes
            prefetch: yes
            num-threads: 2
            so-rcvbuf: 4m
            so-reuseport: yes
            use-caps-for-id: yes
            harden-dnssec-stripped: yes
            # optional configure local zone
            # local-zone: "lala.lan" static
            # local-data: "lala.lan A 127.0.0.1"
            # local-data: "*.lala.lan A 127.0.0.1"  # 
          forward-zone:
            name: "."
            forward-addr: 1.1.1.1
            forward-addr: 2606:4700:4700::1111
            forward-addr: 8.8.8.8
            forward-addr: 2001:4860:4860::8888

      notify: Restart Unbound

    - name: Validate Unbound configuration
      command: unbound-checkconf /etc/unbound/unbound.conf

    - name: Disable DNSStubListener in systemd-resolved
      ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNSStubListener
        value: no

    - name: Stop systemd-resolved early to free port 53
      service:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Enable and start Unbound
      service:
        name: unbound
        enabled: yes
        state: started

    - name: Make resolv.conf use local Unbound and immutable
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 127.0.0.1
          nameserver ::1
      notify: restart unbound

    - name: Protect resolv.conf from overwrites
      file:
        path: /etc/resolv.conf
        mode: '0644'
        owner: root
        group: root

    - name: Create systemd drop-in for Unbound restart policy
      file:
        path: /etc/systemd/system/unbound.service.d
        state: directory
      notify:
        - handler systemd-reload-unbound
        - restart unbound

    - name: Unbound restart drop-in config
      copy:
        dest: /etc/systemd/system/unbound.service.d/restart.conf
        content: |
          [Service]
          Restart=on-failure
          RestartSec=1s
      notify: 
        - handler systemd-reload-unbound
        - restart unbound

    - name: NM dispatcher script only if NetworkManager present
      block:
        - name: Create NM dispatcher for Unbound DNS
          copy:
            dest: /etc/NetworkManager/dispatcher.d/10-unbound-dns
            content: |
              #!/bin/bash
              IFACE=$1
              ACTION=$2
              if [ "$ACTION" = "up" ] || [ "$ACTION" = "dhcp4-change" ] || [ "$ACTION" = "dhcp6-change" ]; then
                CONN=$(nmcli -t -f NAME dev "$IFACE")
                if [ -n "$CONN" ]; then
                  nmcli con mod "$CONN" ipv4.dns "127.0.0.1 ;" ipv4.ignore-auto-dns yes
                  nmcli con mod "$CONN" ipv6.dns "::1 ;" ipv6.ignore-auto-dns yes
                  nmcli con reload
                  nmcli con up "$CONN"
                fi
              fi
            mode: '0755'
          notify: 
          - handler systemd-reload-unbound
          - restart unbound

      when: ansible_facts.service_mgr == "systemd" and "NetworkManager.service" in ansible_facts.services

    - name: Trigger systemd releoad, someties it still cries about chenged config
      ansible.builtin.debug:
        msg: "Triggering handlers"
      changed_when: true
      notify:
        - handler systemd-reload-unbound
        - restart unbound

  handlers:
    - name: handler systemd-reload-unbound
      systemd:
        name: unbound
        state: restarted
        daemon_reload: yes
    
    - name: restart unbound
      service:
        name: unbound
        state: restarted
